#!/usr/bin/env python3
"""Write the numbers and table rows of the manuscript from the two certificate reports.

    python3 code/hh_make_numbers.py          (from the paper's folder, or from anywhere)

Every number of the manuscript that a program prints is taken from data/certify_equilibria_hopf.txt,
data/certify_bistability.txt, data/identify_stable_orbit.txt, data/numerics_h2.txt or data/mutation_study.txt here,
never typed by hand.  The rules:

  * an Arb ball printed as [m +/- r] is read as the exact rational interval [m - r, m + r] (Arb prints a decimal
    ball that contains its ball), and every interval is re-rounded OUTWARD to the number of decimals shown: the
    lower end down, the upper end up, in exact rational arithmetic (fractions.Fraction), never through a float;
  * an interval [lo, hi] or a bound <= x / >= x that a program already rounded outward is copied, or re-rounded
    outward to fewer digits;
  * a number printed by a non-rigorous stage (numerics, the high-precision refinement) is copied as printed and is
    used only where the manuscript labels it numerical;
  * every pattern must match exactly once (or the stated number of times), and the reports must say that every
    check passed; otherwise this program stops, and nothing is written.

The macros and the rows of the generated tables (the unstable branch, the orbits of Theorem 5, the SHA-256 digests of the
programs and reports) go into one marked block of paper/hh-dynamics.tex, between
the lines "% BEGIN generated by code/hh_make_numbers.py" and "% END generated by code/hh_make_numbers.py", which this program
replaces; the manuscript is then one self-contained file, as tools/paper-build.sh expects.
"""
import hashlib
import math
import os
import re
import sys
from fractions import Fraction as Fr

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
DATA = os.path.join(ROOT, 'data')
PAPER = os.path.join(ROOT, 'paper')

HOPF = open(os.path.join(DATA, 'certify_equilibria_hopf.txt')).read()
BIST = open(os.path.join(DATA, 'certify_bistability.txt')).read()
IDENT = open(os.path.join(DATA, 'identify_stable_orbit.txt')).read()
NUMH2 = open(os.path.join(DATA, 'numerics_h2.txt')).read()
MUT = open(os.path.join(DATA, 'mutation_study.txt')).read()

NUM = r'-?[0-9]+(?:\.[0-9]+)?(?:e[+-]?[0-9]+)?'
BALL = r'\[(' + NUM + r') \+/- (' + NUM + r')\]'
IV = r'\[(' + NUM + r'), (' + NUM + r')\]'


class Missing(RuntimeError):
    pass


def one(pat, text, flags=0):
    ms = list(re.finditer(pat, text, flags))
    if len(ms) != 1:
        raise Missing('pattern %r matched %d times' % (pat, len(ms)))
    return ms[0]


def every(pat, text, n, flags=0):
    ms = list(re.finditer(pat, text, flags))
    if len(ms) != n:
        raise Missing('pattern %r matched %d times, expected %d' % (pat, len(ms), n))
    return ms


def block(text, start, end):
    """The text between the unique occurrence of start and the next occurrence of end."""
    i = text.index(start)
    if text.count(start) != 1:
        raise Missing('block start %r is not unique' % start)
    j = text.index(end, i + len(start)) if end else len(text)
    return text[i:j]


# ------------------------------------------------------------------ exact outward formatting
def ball_iv(m, r):
    return Fr(m) - Fr(r), Fr(m) + Fr(r)


def _fixed(q, d, up):
    n = math.ceil(q * 10 ** d) if up else math.floor(q * 10 ** d)
    sign = '-' if n < 0 else ''
    n = abs(n)
    ip, fp = divmod(n, 10 ** d)
    return sign + str(ip) + (('.' + str(fp).zfill(d)) if d > 0 else '')


def lo(q, d):
    return _fixed(Fr(q), d, False)


def hi(q, d):
    return _fixed(Fr(q), d, True)


def iv(a, b, d):
    """'[a, b]' rounded outward to d decimals, as TeX."""
    return '[%s, %s]' % (tex(lo(a, d)), tex(hi(b, d)))


def sci_up(q, sig=2):
    """An upper bound of q > 0 as TeX scientific notation with sig significant digits, rounded up."""
    q = Fr(q)
    E = math.floor(math.log10(float(q)))
    while Fr(10) ** E > q:
        E -= 1
    while Fr(10) ** (E + 1) <= q:
        E += 1
    n = math.ceil(q / Fr(10) ** (E - sig + 1))
    if n >= 10 ** sig:
        E += 1
        n = math.ceil(q / Fr(10) ** (E - sig + 1))
    ds = str(n)
    mant = ds[0] + (('.' + ds[1:]) if len(ds) > 1 else '')
    return '%s\\cdot 10^{%d}' % (mant, E)


def tex(s):
    """A decimal string as TeX (the minus sign stays a hyphen-minus; TeX math makes it a minus)."""
    return s


def sci_tex(s):
    """'2.25e-09' -> '2.25\\cdot 10^{-9}'."""
    m = re.fullmatch(r'(-?[0-9.]+)e([+-]?)0*([0-9]+)', s)
    if not m:
        return s
    return '%s\\cdot 10^{%s%s}' % (m.group(1), '-' if m.group(2) == '-' else '', m.group(3))


MAC = {}


def mac(name, value):
    if not re.fullmatch(r'[A-Za-z]+', name):
        raise ValueError('macro name %r' % name)
    if name in MAC:
        raise ValueError('macro %s defined twice' % name)
    MAC[name] = str(value)


# ================================================================== the Hopf report
m = one(r'(\d+) checks, 0 failed: (\d+) proof checks, (\d+) consistency checks, (\d+) negative controls, '
        r'(\d+) self-tests, (\d+) cross-checks', HOPF)
if 'FAIL' in HOPF:
    raise SystemExit('the Hopf report contains a failed check')
for k, v in zip(('HopfChecks', 'HopfProof', 'HopfConsistency', 'HopfControls', 'HopfSelftests', 'HopfCross'),
                m.groups()):
    mac(k, v)
assert sum(int(x) for x in m.groups()[1:]) == int(m.group(1))
mac('HopfTime', '%d' % round(float(one(r'run time ([0-9.]+) s', HOPF).group(1))))
mac('HopfLedger', one(r'printed with outward rounding \((\d+) of them\)', HOPF).group(1))
mac('HopfVersions', one(r'python-flint (\S+) on FLINT (\S+);', HOPF).group(0)[:-1])
mac('NpiecesSlope', one(r'\[(\d+) pieces\]', HOPF).group(1))
m = one(r'\[(\d+) pieces, (\d+) undecided tiny pieces\]', HOPF)
mac('NpiecesHurwitz', m.group(1))
mac('Nundecided', m.group(2))
mac('JssBoundHigh', one(r'127 >= (' + NUM + r')\]', HOPF).group(1))
mac('JssMinusTwelve', one(r'Jss\(-12\) <= (' + NUM + r')\]', HOPF).group(1))
m = one(r'exactly two clusters\s+\[\[(' + NUM + '), (' + NUM + r')\], \[(' + NUM + '), (' + NUM + r')\]\]', HOPF)
mac('ClusterOne', '[%s, %s]' % m.group(1, 2))
mac('ClusterTwo', '[%s, %s]' % m.group(3, 4))
for i, nm in ((1, 'One'), (2, 'Two')):
    m = one(r'cluster %d: .*?\[dD3/du in ' % i + IV + ' on the cluster', HOPF)
    mac('dDthree' + nm, '[%s, %s]' % m.group(1, 2))
    m = one(r'u_H%d in ' % i + IV + r', radius <= (' + NUM + ')', HOPF)
    mac('uH' + nm, iv(Fr(m.group(1)), Fr(m.group(2)), 30))
    mac('uH' + nm + 'short', iv(Fr(m.group(1)), Fr(m.group(2)), 12))
    mac('uH' + nm + 'rad', sci_tex(m.group(3)))
m = one(r'E_l\* = ' + BALL, HOPF)
a, b = ball_iv(*m.groups())
mac('ELstar', iv(a, b, 25))
mac('ELstarShort', lo(a, 13))                      # 10.5989209693916 (a lower bound; used with \ldots)
m = one(r'is 0\.3 \(E_l\* - 10\.613\) in ' + IV, HOPF)
mac('Irest', '[%s, %s]' % m.group(1, 2))
mac('IrestShort', hi(Fr(m.group(1)), 6))           # -0.004223 (with \ldots)
m = one(r'E_l\* in ' + IV + r'\]', HOPF)
mac('ELstarCheck', '[%s, %s]' % m.group(1, 2))

ENAMES = tuple((t, re.escape(e)) for t, e in (('HH', '10.613 (Hodgkin and Huxley)'),
                                              ('Star', 'E_l* (zero resting current)'),
                                              ('GO', '10.599 (Guckenheimer and Oliva)'), ('Lo', '10.59'),
                                              ('Hi', '10.62')))
for i, nm in ((1, 'One'), (2, 'Two')):
    blk = block(HOPF, '   H%d: u_H%d in' % (i, i), '[crosscheck] H%d: independent cross-check (SymPy' % i)
    for tag, en in ENAMES:
        m = one(r'J_H%d for E_l = %s: ' % (i, en) + IV, blk)
        mac('JH' + nm + tag, iv(Fr(m.group(1)), Fr(m.group(2)), 12))
        mac('JH' + nm + tag + 'long', '[%s, %s]' % m.group(1, 2))
    m = one(r'over E_l in \[10\.59, 10\.62\]: J_H%d in ' % i + IV, blk)
    mac('JH' + nm + 'Range', '[%s, %s]' % m.group(1, 2))
    m = one(r'omega_H%d in ' % i + IV + r', period 2 pi/omega in ' + IV + ' ms', blk)
    mac('om' + nm, iv(Fr(m.group(1)), Fr(m.group(2)), 12))
    mac('Per' + nm, iv(Fr(m.group(3)), Fr(m.group(4)), 9))
    m = one(r'Re d lambda/du in ' + IV + r', dJss/du in ' + IV + r', Re d lambda/dJ in ' + IV, blk)
    mac('dlu' + nm, iv(Fr(m.group(1)), Fr(m.group(2)), 10 if i == 1 else 10))
    mac('dJu' + nm, iv(Fr(m.group(3)), Fr(m.group(4)), 8))
    mac('dlJ' + nm, iv(Fr(m.group(5)), Fr(m.group(6)), 11))
    m = one(r'l1 in ' + IV + r' \(with <q, q> = 1', blk)
    mac('lone' + nm, '[%s, %s]' % m.group(1, 2))
    m = one(r'\|q_u\| in ' + IV + r' .*?; 16 \|q_u\|\^2 Re\(d lambda/dJ\)/\(omega l1\) in ' + IV, blk)
    mac('qu' + nm, '[%s, %s]' % m.group(1, 2))
    mac('Slope' + nm, '[%s, %s]' % m.group(3, 4))
    mac('SlopeShort' + nm, lo(Fr(m.group(3)), 2))
    m = one(r'\[crosscheck\] H%d: .*?mpmath l1 = (' % i + NUM + r'), relative difference (' + NUM + ')', HOPF)
    mac('Crossrel' + nm, sci_tex(m.group(2)) if 'e' in m.group(2) else m.group(2))
    m = one(r'\[crosscheck\] H%d: independent cross-check of the transversality .*?relative differences (' % i + NUM
            + '), (' + NUM + ')', HOPF)
    mac('Transrel' + nm, sci_tex(max((Fr(m.group(1)), m.group(1)), (Fr(m.group(2)), m.group(2)))[1]))
mac('JHoneMinBall', one(r'J_H1 >= (' + NUM + r') on the ball', HOPF).group(1))
m = one(r'excludes 0, so it is not passed away from a Hopf point\s+\[a2 - omega\^2 - a4/omega\^2 in ' + IV, HOPF)
mac('SplitControl', '[%s, %s]' % m.group(1, 2))
tests = every(r'l1 routine on the (planar|coupled), omega = (1|3/2) test system reproduces the known l1\s+\[known l1 in '
              + IV, HOPF, 4)
for mm, nm in zip(tests, ('PlanarA', 'PlanarB', 'CoupledA', 'CoupledB')):
    mac('Test' + nm, '[%s, %s]' % mm.group(3, 4))
m = every(r'misses the known l1 of the coupled test system\s+\[mutated routine in ' + IV, HOPF, 2)
mac('MutSign', '[%s, %s]' % m[0].group(1, 2))
mac('MutTwoiw', '[%s, %s]' % m[1].group(1, 2))

# ================================================================== the bistability report
if re.search(r'\[FAIL\]', BIST) or 'STOPPED' in BIST:
    raise SystemExit('the bistability report contains a failed check')
m = one(r'(\d+) checks passed: (\d+) proof checks, (\d+) negative controls, (\d+) self-tests, (\d+) numerical-only '
        r'checks;', BIST)
for k, v in zip(('BiChecks', 'BiProof', 'BiControls', 'BiSelftests', 'BiNumerical'), m.groups()):
    mac(k, v)
assert sum(int(x) for x in m.groups()[1:]) == int(m.group(1))
m = one(r'total run time ([0-9.]+) s \(([0-9.]+) min\)', BIST)
mac('BiTimeMin', m.group(2))
mac('BiTimeFourB', '%d' % round(float(one(r'stage 4b time ([0-9.]+) s \(wall\)', BIST).group(1))))
mac('BiTimeNumerics', '%d' % round(float(one(r'numerics time ([0-9.]+)s', BIST).group(1))))
mac('BiWorkers', one(r'STAGE 4b .*?\(proof, 60 pieces, (\d+) worker processes\)', BIST).group(1))
mac('BiCkpt', one(r'pieces read back from the checkpoint of an earlier run of the same code: (\d+)', BIST).group(1))
if MAC['BiCkpt'] != '0' or 'read from the checkpoint' in BIST or 'debug: numerics loaded' in BIST:
    raise SystemExit('the committed report must come from one run that computed every piece and its own candidates')
mac('BiLedger', one(r'every decimal bound printed in stages 3-7 \((\d+) of them\)', BIST).group(1))
m = one(r'python-flint (\S+) \(Arb ball arithmetic\), working precision (\d+) bits, Taylor order (\d+), remainder '
        r'tolerance (\S+) \(relative to scales \[([^\]]+)\]\)', BIST)
mac('FlintVersion', m.group(1))
mac('BiPrec', m.group(2))
mac('BiOrder', m.group(3))
mac('BiTol', sci_tex(m.group(4)))
mac('FLINTVersion', one(r'on FLINT (\S+) \(Arb ball arithmetic, 96 bits\)', BIST.split('STAGE 1')[0]).group(1))
mac('PythonVersion', one(r'Python (\S+) integers and fractions', BIST.split('STAGE 1')[0]).group(1))
mac('BiStageOneTests', str(len(re.findall(r'\[PASS\]', block(BIST, 'STAGE 1 ', 'STAGE 2 ')))))
mac('BiStageOneNeg', str(len(re.findall(r'\[PASS\] NEG', block(BIST, 'STAGE 1 ', 'STAGE 2 ')))))

# stage 3: the equilibrium over the E_l ball
s3 = block(BIST, 'STAGE 3 ', 'STAGE 4 ')
m = one(r'equilibrium box: u=' + BALL + r', m=' + BALL + r', n=' + BALL + r', h=' + BALL, s3)
g = m.groups()
for k, (nm, d) in enumerate((('u', 5), ('m', 7), ('n', 7), ('h', 5))):
    a, b = ball_iv(g[2 * k], g[2 * k + 1])
    mac('EqBox' + nm, iv(a, b, d))
m = one(r'a1 = ' + BALL + r', a2 = ' + BALL + r', a3 = ' + BALL + r', a4 = ' + BALL, s3)
g = m.groups()
for k, nm in enumerate(('One', 'Two', 'Three', 'Four')):
    a, b = ball_iv(g[2 * k], g[2 * k + 1])
    mac('EqA' + nm, iv(a, b, 4))
m = one(r'a1 a2 - a3 = ' + BALL + r' > 0, \(a1 a2 - a3\) a3 - a1\^2 a4 = ' + BALL, s3)
a, b = ball_iv(*m.group(1, 2))
mac('EqDtwo', iv(a, b, 3))
a, b = ball_iv(*m.group(3, 4))
mac('EqDthree', iv(a, b, 3))
m = one(r'U = ' + BALL + r", F'\(U\) = " + BALL + r', N\(U\) = ' + BALL, s3)
mac('EqNewtonU', iv(*ball_iv(*m.group(1, 2)), 5))
mac('EqNewtonDF', iv(*ball_iv(*m.group(3, 4)), 4))
mac('EqNewtonN', iv(*ball_iv(*m.group(5, 6)), 5))
m = one(r"F' > 0 on W = \[(" + NUM + '), (' + NUM + r')\] \((\d+) pieces\)', s3)
mac('EqW', '[%s, %s]' % m.group(1, 2))
mac('EqWpieces', m.group(3))
mac('EqExcl', one(r'outside W \((\d+) interval evaluations\)', s3).group(1))
m = one(r'F >= 0\.3 \(115 - E\) - J = ' + BALL, s3)
mac('EqHighBound', lo(ball_iv(*m.groups())[0], 2))
discs = one(r'radii include the rounding\): (.*)\n', s3).group(1)
dm = every(r'(-?[0-9.]+)([+-][0-9.]+)i \(radius (' + NUM + r')\)', discs, 4)
for mm, nm in zip(dm, ('One', 'Two', 'Three', 'Four')):
    mac('EqDisc' + nm, mm.group(1))
    mac('EqDiscIm' + nm, mm.group(2).lstrip('+'))
    mac('EqDiscR' + nm, sci_tex(mm.group(3)))
EVALS = (('HH', r'10\.613 \(Hodgkin-Huxley\)'), ('Star', r'E_l\* = \[[^\]]*\] \(exact zero-current value\)'),
         ('GO', r'10\.599 \(Guckenheimer-Oliva\)'))
for tag, en in EVALS:
    m = one(r'E_l = ' + en + r': equilibrium u\* in ' + BALL, s3)
    mac('uStar' + tag, iv(*ball_iv(*m.groups()), 12))
# the ball about E_l* on which Theorem 5 is proved is the program's internal ball; the report prints Arb's decimal
# enclosure of it, which is larger.  A domain of validity must not be rounded outward, so the printed ball is copied
# as printed and the manuscript says that it contains the ball of the proof.
m = one(r'E_l = E_l\* = ' + BALL + r' \(exact zero-current value\): equilibrium', s3)
mac('ELstarBiPrinted', '[%s \\pm %s]' % (m.group(1), sci_tex(m.group(2))))

# stage 4: the orbits at the three values (step counts, extremes, box radii)
s4 = block(BIST, 'STAGE 4 ', 'STAGE 4b ')
S4 = {}
for tag, en in EVALS:
    i = re.search(r'  --- E_l = ' + en, s4).start()
    j = s4.find('  --- E_l = ', i + 5)
    S4[tag] = s4[i:(j if j > 0 else len(s4))]
for tag, blk in S4.items():
    ex = every(r'u along the orbit: stays in ' + IV + r' mV, attains u <= (' + NUM + r') and u >= (' + NUM + ')', blk, 2)
    mac('SmaxLo' + tag, ex[0].group(4))
    mac('SminHi' + tag, ex[0].group(3))
    mac('Srange' + tag, '[%s, %s]' % ex[0].group(1, 2))
    mac('UmaxHi' + tag, ex[1].group(2))
    mac('Urange' + tag, '[%s, %s]' % ex[1].group(1, 2))
    st = every(r'first return certified \((\d+) downward passes of the section, no other upward crossing\), (\d+) steps',
               blk, 2)
    mac('Ssteps' + tag, st[0].group(2))
    mac('Usteps' + tag, st[1].group(2))
    mac('Spasses' + tag, st[0].group(1))
    mac('Upasses' + tag, st[1].group(1))
    rr = every(r'C\^1 run over Z \(radius \[([0-9.e +-]+)\]\): DP radius (' + NUM + ')', blk, 2)
    mac('SboxRad' + tag, sci_tex('%.2e' % max(float(x) for x in rr[0].group(1).split())))
    mac('UboxRad' + tag, sci_tex('%.2e' % max(float(x) for x in rr[1].group(1).split())))
    mac('UboxRadMin' + tag, sci_tex('%.2e' % min(float(x) for x in rr[1].group(1).split())))
    mac('SDPrad' + tag, sci_tex(rr[0].group(2)))
    mac('UDPrad' + tag, sci_tex(rr[1].group(2)))

# stage 7: Theorem B, outward-rounded values
s7 = block(BIST, 'STAGE 7 ', None)
TB = {}
for tag, en in EVALS:
    i = re.search(r'  Theorem B \(E_l = ' + en + r'\)\.', s7).start()
    j = s7.find('  Theorem B (E_l = ', i + 5)
    if j < 0:
        j = s7.find('  Theorem C', i)
    TB[tag] = s7[i:j]
ROWS = []
for tag, blk in TB.items():
    pts = every(r'\{u = (20|5), du/dt > 0\} at \(m,n,h\) in ' + BALL + ', ' + BALL + ', ' + BALL, blk, 2)
    for which, mm in zip(('S', 'U'), pts):
        g = mm.groups()[1:]
        for k, nm in enumerate('mnh'):
            a, b = ball_iv(g[2 * k], g[2 * k + 1])
            mac(which + 'pt' + nm + tag, iv(a, b, 11))
    m = one(r'minimal period T_s in ' + BALL + ' ms', blk)
    Ts = ball_iv(*m.groups())
    mac('Ts' + tag, iv(*Ts, 11))
    m = one(r'\|mu_1 - (' + NUM + r')\| <= (' + NUM + r'), \|mu_2\|, \|mu_3\| <= (' + NUM + ')', blk)
    mac('SmuOne' + tag, m.group(1))
    mac('SmuOneR' + tag, sci_tex(m.group(2)))
    mac('SmuRest' + tag, sci_tex(m.group(3)))
    m = one(r'minimal period T_u in ' + BALL + ' ms', blk)
    Tu = ball_iv(*m.groups())
    mac('Tu' + tag, iv(*Tu, 8))
    m = one(r'mu_1 real in ' + IV + r' \(> 1\)', blk)
    mac('UmuOne' + tag, '[%s, %s]' % m.group(1, 2))
    m = one(r'\|mu_2 - (' + NUM + r')\| <= (' + NUM + r'), \|mu_3\| <= (' + NUM + ')', blk)
    mac('UmuTwo' + tag, m.group(1))
    mac('UmuTwoR' + tag, sci_tex(m.group(2)))
    mac('UmuThree' + tag, sci_tex(m.group(3)))
m = one(r'it lies in the box ' + BALL + ', ' + BALL + ', ' + BALL + ', ' + BALL + ' and is', s7)
m = one(r'\[10\.59, 10\.62\] at J = 8 is the current interval J in \[([0-9.]+), ([0-9.]+)\] at E_l = 10\.613', s7)
mac('JequivLo', m.group(1))
mac('JequivHi', m.group(2))
m = one(r'minimal period in \[(' + NUM + '), (' + NUM + r')\] ms, reaching u >= (' + NUM + r') mV \(a spike\)', s7)
mac('TballLo', m.group(1))
mac('TballHi', m.group(2))
mac('UballMax', m.group(3))
mac('TballLoShort', lo(Fr(MAC['TballLo']), 4))
mac('TballHiShort', hi(Fr(MAC['TballHi']), 4))
# the firing frequency 1000/T in Hz, rounded outward from the proved period interval
mac('FreqLo', lo(Fr(1000) / Fr(MAC['TballHi']), 3))
mac('FreqHi', hi(Fr(1000) / Fr(MAC['TballLo']), 3))
mac('Normball', one(r'nontrivial Floquet multipliers satisfy \|mu\| <= (' + NUM + r'): orbitally', s7).group(1))

# stage 4b: the 60 pieces
s4b = block(BIST, 'STAGE 4b ', 'STAGE 5 ')
pieces = every(r'E_l in \[([0-9.]+), ([0-9.]+)\]: P\(Z\) in int Z True, runs cover Z x piece True, sup\|\|DP\|\|_inf <= ([0-9.]+), '
               r'T in \[([0-9.]+), ([0-9.]+)\], box radius ~(' + NUM + r'), (\d+)s', s4b, 60)
mac('NPieces', str(len(pieces)))
mac('PieceWidth', '5\\cdot 10^{-4}')
assert all(Fr(p.group(2)) - Fr(p.group(1)) == Fr(1, 2000) for p in pieces)
norms = sorted((Fr(p.group(3)), p.group(3)) for p in pieces)
mac('NormMax', norms[-1][1])
mac('NormMin', norms[0][1])
times = [int(p.group(7)) for p in pieces]
mac('PieceTimeMin', str(min(times)))
mac('PieceTimeMax', str(max(times)))
rads = {p.group(6) for p in pieces}
mac('PieceBoxRad', sci_tex(sorted(rads)[0]) if len(rads) == 1 else 'several')
m = one(r'over the whole ball: period in \[([0-9.]+), ([0-9.]+)\] ms, multipliers \|mu\| <= ([0-9.]+), u reaches >= '
        r'([0-9.]+)', s4b)
if (m.group(1), m.group(2), m.group(3), m.group(4)) != (MAC['TballLo'], MAC['TballHi'], MAC['Normball'],
                                                         MAC['UballMax']):
    raise SystemExit('stage 4b and stage 7 disagree')
mac('dzdE', one(r'dz\*/dE_l = \[([^\]]+)\]', s4b).group(1).split()[0])

# stage 5: the controls
s5 = block(BIST, 'STAGE 5 ', 'STAGE 6 ')
m = one(r'u\* in ' + BALL + r', a1 a2 - a3 = ' + BALL + r', \(a1 a2 - a3\) a3 - a1\^2 a4 = ' + BALL, s5)
mac('CtlTwentyU', iv(*ball_iv(*m.group(1, 2)), 3))
mac('CtlTwentyDtwo', iv(*ball_iv(*m.group(3, 4)), 2))
mac('CtlTwentyDthree', iv(*ball_iv(*m.group(5, 6)), 2))
mac('CtlNorm', one(r'every member of DP\(Z\) has \|\|DP\|\|_inf >= (' + NUM + ')', s5).group(1))
mac('CtlKappaHi', one(r'which the upper bound of the enclosure, sup \|\|DP_E\|\|_inf <= (' + NUM + r'), does not meet', s5).group(1))
kv = every(r'K vs Z: max \|mid K - zbar\| / radius\(Z\) = (' + NUM + r'), K in int Z: False', s5, 5)
mac('CtlKJ', sci_tex('%.1e' % float(kv[4].group(1))))

# stage 2: numerics (copied as printed; numerical only)
s2 = block(BIST, 'STAGE 2 ', 'STAGE 3 ')
mac('NumRest', sci_tex(one(r'rest state at J = 0: u = (' + NUM + ') mV', s2).group(1)))
m = one(r'I_ss\(-12\) = (' + NUM + r'), I_ss\(250\) = (' + NUM + ')', s2)
mac('NumIssTwoFifty', m.group(2))
m = every(r'fold of limit cycles .*?: J_LPC = (' + NUM + r'), period (' + NUM + ') ms', s2, 2)
mac('FoldHH', m[0].group(1))
mac('FoldStar', m[1].group(1))
mac('FoldPeriod', m[0].group(2))
br = every(r'unstable branch towards the Hopf point: J = (' + NUM + r'), period (' + NUM + r'), u in \[(' + NUM + '), ('
           + NUM + r')\] \(amplitude (' + NUM + r')\), unstable multiplier (' + NUM + ')', s2, 5)
BRANCH = [tuple(x.groups()) for x in br]
m = one(r'stable orbit \(section u = 20, u increasing\): z = .*?period (' + NUM + r') ms, u in \[(' + NUM + '), (' + NUM
        + r')\], multipliers \[\s*(' + NUM + ')', s2)
mac('NumTs', m.group(1))
mac('NumSumax', m.group(3))
m = one(r'an unstable orbit .*?delta u = (' + NUM + r'); section u = 5, u increasing\): z = .*?period (' + NUM
        + r') ms, u in \[(' + NUM + '), (' + NUM + ')', s2, re.S)
mac('NumDeltaU', m.group(1))

# stage 6: the high-precision refinement (not a proof)
s6 = block(BIST, 'STAGE 6 ', 'STAGE 7 ')
m = every(r'return time from this point = \[([0-9.]+) \+/- ', s6, 2)
mac('HpTs', m[0].group(1)[:26])
mac('HpTu', m[1].group(1)[:26])
m = every(r'nontrivial multipliers \(eigenvalues of mid DP; DP radius (' + NUM + r')\): \[([0-9.e+-]+) \+/- [^\]]*\], '
          r'\[([0-9.e+-]+) \+/- [^\]]*\], \[([0-9.e+-]+) \+/- [^\]]*\]', s6, 2)
mac('HpSmu', m[0].group(2)[:22])
mac('HpUmuOne', m[1].group(2)[:22])
mac('HpUmuTwo', m[1].group(3)[:22])

# ================================================================== the identification of the stable orbits (Corollary 7)
if re.search(r'\[FAIL\]', IDENT) or 'STOPPED' in IDENT:
    raise SystemExit('the identification report contains a failed check')
m = one(r'(\d+) checks passed: (\d+) proof checks, (\d+) negative controls, (\d+) cross-checks', IDENT)
for k, v in zip(('IdChecks', 'IdProof', 'IdControls', 'IdCross'), m.groups()):
    mac(k, v)
assert sum(int(x) for x in m.groups()[1:]) == int(m.group(1))
mac('IdTime', '%d' % round(float(one(r'run time ([0-9.]+) s', IDENT).group(1))))
mac('IdLedger', one(r'printed with outward rounding \((\d+) of them\)', IDENT).group(1))
offs = every(r'K lies in the interior of its box \(centre of K about ([0-9.]+) box radii from the centre of the box\)',
             IDENT, 5)
mac('IdOffMax', max((Fr(x.group(1)), x.group(1)) for x in offs)[1])
ctl = every(r'centre of K about ([0-9.]+) box radii away\): the inclusion must fail', IDENT, 3)
mac('IdCtlMin', min((Fr(x.group(1)), x.group(1)) for x in ctl)[1])
idp = every(r'E_l in \[([0-9.]+), ([0-9.]+)\]: P\(Z\) in int Z True, runs cover Z x piece True, sup\|\|DP\|\|_inf <= ([0-9.]+), T in \[([0-9.]+), '
            r'([0-9.]+)\], box radius ~(' + NUM + ')', IDENT, 4)
mac('IdPieces', ', '.join('$[%s, %s]$' % x.group(1, 2) for x in idp))
for x in idp:                                  # the same lines as stage 4b of the committed run
    if x.group(0) not in BIST:
        raise SystemExit('identification piece line not in the committed stage 4b: ' + x.group(0))

# ================================================================== the small cycles below J_H2 (numerical)
h2 = every(r'J_H2 - J = ([0-9.]+) \(J = ([0-9.]+)\).*?\n.*?\n    Newton on .*?period ([0-9.]+) ms, nontrivial multipliers '
           r'([0-9.]+), ([0-9.]+), ([0-9.]+)\n    peak-to-peak u ([0-9.]+) mV, .*?= ([0-9.]+)', NUMH2, 3, re.S)
for x, nm in zip(h2, ('A', 'B', 'C')):
    mac('HtwoDelta' + nm, '%g' % float(x.group(1)))
    mac('HtwoRatio' + nm, '%.2f' % float(x.group(8)))
mac('HtwoMuMax', '%.3f' % max(float(x.group(4)) for x in h2))
(d1, r1), (d2, r2) = sorted((Fr(x.group(1)), Fr(x.group(7)) ** 2 / Fr(x.group(1))) for x in h2)[:2]
mac('HtwoExtrap', '%.2f' % float(r1 - (r2 - r1) / (d2 - d1) * d1))

# ================================================================== the mutation study (not a proof)
if 'STUDY STOPPED' in MUT or 'harness-error' in MUT or 'Full list of mutations: True' not in MUT:
    raise SystemExit('the mutation study did not complete, or did not run the full list')
m = one(r'Summary: (\d+) mutations; (\d+) of the (\d+) not marked weak stopped the program \((\d+) at a failed check, '
        r'(\d+) by an exception\); (\d+) marked weak, of which (\d+) passed\.', MUT)
for k, v in zip(('MutTotal', 'MutStopped', 'MutStrong', 'MutByCheck', 'MutByExc', 'MutWeak', 'MutWeakPassed'),
                m.groups()):
    mac(k, v)
if one(r'Every mutation not marked weak was stopped: (\w+)', MUT).group(1) != 'True':
    raise SystemExit('a mutation not marked weak was not stopped')
if 'skipped (--no-baseline)' in MUT:
    raise SystemExit('the committed mutation study must include the baselines')
mac('MutTime', '%d' % round(float(one(r'run time ([0-9.]+) s', MUT).group(1)) / 60))

# ================================================================== the amplitude table (numerical)
ROWS = {}
JH1 = Fr(MAC['JHOneHHlong'].strip('[]').split(', ')[0])
rows = []
for J, T, ulo, uhi, amp, mu in BRANCH:
    d = JH1 - Fr(J)
    ratio = Fr(amp) ** 2 / d
    rows.append('%s & %s & %s & %s & %s \\\\' % (J, T, amp, '%.4f' % float(d), '%.2f' % float(ratio)))
ROWS['TabBranchRows'] = rows
# numerical: linear extrapolation to J = J_H1 of (amplitude)^2/(J_H1 - J) through the two orbits closest to H1
(d1, r1), (d2, r2) = sorted((JH1 - Fr(J), Fr(amp) ** 2 / (JH1 - Fr(J))) for J, T, ulo, uhi, amp, mu in BRANCH)[:2]
mac('ExtrapRatio', '%.2f' % float(r1 - (r2 - r1) / (d2 - d1) * d1))
mac('FoldFreq', '%.1f' % (1000 / float(MAC['FoldPeriod'])))

# ================================================================== the orbit tables (Theorem 5)
lab = {'HH': '$10.613$', 'Star': '$E_l^*$', 'GO': '$10.599$'}
ROWS['TabStableRows'] = [r'%s & $%s$ & $|\mu_1 - %s| \le %s$ & $%s$ \\' % (
    lab[tag], MAC['Ts' + tag], MAC['SmuOne' + tag], MAC['SmuOneR' + tag], MAC['SmuRest' + tag])
    for tag in ('HH', 'Star', 'GO')]
ROWS['TabUnstableRows'] = [r'%s & $%s$ & $%s$ & $|\mu_2 - %s| \le %s$ & $%s$ \\' % (
    lab[tag], MAC['Tu' + tag], MAC['UmuOne' + tag], MAC['UmuTwo' + tag], MAC['UmuTwoR' + tag], MAC['UmuThree' + tag])
    for tag in ('HH', 'Star', 'GO')]

# ================================================================== SHA-256 of the programs and reports
FILES = ['code/certify_equilibria_hopf.py', 'code/hh_ball.py', 'code/certify_bistability.py', 'code/hh_arb.py',
         'code/hh_lohner.py', 'code/certlib.py', 'code/ball_stable.py', 'code/outward.py', 'code/tests_integrator.py',
         'code/testsys.py', 'code/shoot_float.py', 'code/hh_numerics.py', 'code/identify_stable_orbit.py',
         'code/mutation_study.py', 'data/certify_equilibria_hopf.txt', 'data/certify_bistability.txt',
         'data/identify_stable_orbit.txt', 'data/mutation_study.txt']
ROWS['TabFilesRows'] = [r'\texttt{%s} & \texttt{%s} \\' % (
    fn.replace('_', r'\_'), hashlib.sha256(open(os.path.join(ROOT, fn), 'rb').read()).hexdigest()[:16]) for fn in FILES]

# ================================================================== write the block into the manuscript
TEX = os.path.join(PAPER, 'hh-dynamics.tex')
BEGIN = '% BEGIN generated by code/hh_make_numbers.py'
END = '% END generated by code/hh_make_numbers.py'
out = [BEGIN + ' from the reports in data/; do not edit by hand.',
       '% Intervals are rounded outward from the printed balls; rerun the programs, then python3 code/hh_make_numbers.py.']
for k in sorted(MAC):
    v = MAC[k]
    if re.fullmatch(r'\[[^\[\]]+, [^\[\]]+\]', v):
        v = v.replace(', ', ',\\allowbreak ')       # an interval may break after its comma
    out.append('\\newcommand{\\%s}{%s}' % (k, v))
for k in sorted(ROWS):
    out.append('\\newcommand{\\%s}{%%\n%s}' % (k, '\n'.join(ROWS[k])))
out.append(END)
src = open(TEX).read()
if src.count(BEGIN) != 1 or src.count(END) != 1:
    raise SystemExit('the manuscript must contain the generated block exactly once')
i, j = src.index(BEGIN), src.index(END) + len(END)
new = src[:i] + '\n'.join(out) + src[j:]
if new != src:
    open(TEX, 'w').write(new)
print('%d macros and %d table-row macros written into %s' % (len(MAC), len(ROWS), os.path.relpath(TEX)))
